apiVersion: v1
kind: Service
metadata:
  name: ssdemo-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ssdemo-apache-php
---
apiVersion: apps/v1
kind: Deployment # リソースの種類
metadata:
  name: ssdemo-deployment # Deploymentの名前
spec:
  replicas: 2 # 起動するpod数
  selector:
    matchLabels:
      app: ssdemo-apache-php
  template:
    metadata:
      labels:
        app: ssdemo-apache-php # podの名前
    spec:
      containers:
      - name: ssdemo-apache-php # コンテナ名
        image: shiratsu2009/php-docker:1.0.0 # コンテナイメージ
        imagePullPolicy: IfNotPresent # ローカルのdocker imageを使用
        ports:
        - containerPort: 80 # コンテナのポート
        volumeMounts:
        - mountPath: /var/www/html/
          name: demo-volume
      volumes:
      - name: demo-volume
        hostPath:
          # directory location on host
          path: /Users/hiratsukashunsuke/vscode/kube_php_work/app
          # this field is optional
          type: Directory